import { Box } from "@mui/material";
import Head from "next/head";
import HomeComponent from "@/components/Home";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Framer motion App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeComponent />
    </Box>
  );
}
